[workspace]
resolver = "2"
members = [
  "macro",
  "runtime",
  "tool",
  "example",
  "common",
]
[workspace.package]
version = "0.5.0"
authors = [
  "Jason Boatman",
  "Shadaj Laddad <shadaj@users.noreply.github.com>"
]
